### PR TITLE
feat: add github-action

### LINKED ISSUE #2: Implement Github Action
First working version: https://github.com/rndmh3ro/antsichaut-action/

### PR DESCRIPTION
**Pull request by gardar**
Adoption of the action from https://github.com/rndmh3ro/antsichaut-action since I felt like the action got a bit lost in a separate repo.

fixes #2

### CODE REVIEW

**Comment by rndmh3ro** [comment]
Thanks, initially I didn't want to further develop the action and actually thought it didn't work. :)
But since you're using it it seems to work. :)

The missing parameters can be added once someone needs them.

**Comment by rndmh3ro** [comment]
Can you please make an exception for the spelling-problems found?

**Comment by gardar** [comment]
> Thanks, initially I didn't want to further develop the action and actually thought it didn't work. :)
> But since you're using it it seems to work. :)

Haha that's funny, yeah it's working fine, I didn't know it wasn't supposed to work :grinning: 

> Can you please make an exception for the spelling-problems found?

I think I got it, added regex to ignore code blocks in markdown according to this: https://github.com/streetsidesoftware/vscode-spell-checker/issues/202#issuecomment-377477473

**Review by rndmh3ro — APPROVED** [review]

**Comment by rndmh3ro** [comment]
Thank you!

**Pull request merged**
